export const monacoLanguages = [
  "abap",
  "apex",
  "azcli",
  "bat",
  "c",
  "clojure",
  "coffeescript",
  "cpp",
  "csharp",
  "css",
  "dart",
  "dockerfile",
  "fsharp",
  "go",
  "graphql",
  "handlebars",
  "html",
  "ini",
  "java",
  "javascript",
  "json",
  "json5",
  "julia",
  "kotlin",
  "less",
  "lua",
  "markdown",
  "objective-c",
  "pascal",
  "perl",
  "php",
  "plaintext",
  "powershell",
  "pug",
  "python",
  "r",
  "razor",
  "ruby",
  "rust",
  "sb",
  "scss",
  "shell",
  "sql",
  "swift",
  "typescript",
  "vb",
  "xml",
  "yaml",
  "toml",
  "hcl",
  "csv",
  "diff",
  "vue",
  "tsx",
  "jsx",
  "makefile",
];

export const monacoLanguagesForReactSelect = [
  { value: "abap", label: "ABAP" },
  { value: "apex", label: "Apex" },
  { value: "azcli", label: "Azure CLI" },
  { value: "bat", label: "Batch" },
  { value: "c", label: "C" },
  { value: "clojure", label: "Clojure" },
  { value: "coffeescript", label: "CoffeeScript" },
  { value: "cpp", label: "C++" },
  { value: "csharp", label: "C#" },
  { value: "css", label: "CSS" },
  { value: "dart", label: "Dart" },
  { value: "dockerfile", label: "Dockerfile" },
  { value: "fsharp", label: "F#" },
  { value: "go", label: "Go" },
  { value: "graphql", label: "GraphQL" },
  { value: "handlebars", label: "Handlebars" },
  { value: "html", label: "HTML" },
  { value: "html + css", label: "HTML + CSS" },
  { value: "ini", label: "INI" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JavaScript" },
  { value: "json", label: "JSON" },
  { value: "json5", label: "JSON5" },
  { value: "julia", label: "Julia" },
  { value: "kotlin", label: "Kotlin" },
  { value: "less", label: "Less" },
  { value: "lua", label: "Lua" },
  { value: "markdown", label: "Markdown" },
  { value: "objective-c", label: "Objective-C" },
  { value: "pascal", label: "Pascal" },
  { value: "perl", label: "Perl" },
  { value: "php", label: "PHP" },
  { value: "plaintext", label: "Plain Text" },
  { value: "powershell", label: "PowerShell" },
  { value: "pug", label: "Pug" },
  { value: "python", label: "Python" },
  { value: "r", label: "R" },
  { value: "razor", label: "Razor" },
  { value: "ruby", label: "Ruby" },
  { value: "rust", label: "Rust" },
  { value: "sb", label: "SB" },
  { value: "scss", label: "SCSS" },
  { value: "shell", label: "Shell" },
  { value: "sql", label: "SQL" },
  { value: "swift", label: "Swift" },
  { value: "typescript", label: "TypeScript" },
  { value: "vb", label: "Visual Basic" },
  { value: "xml", label: "XML" },
  { value: "yaml", label: "YAML" },
  { value: "toml", label: "TOML" },
  { value: "hcl", label: "HCL" },
  { value: "csv", label: "CSV" },
  { value: "diff", label: "Diff" },
  { value: "vue", label: "Vue" },
  { value: "tsx", label: "TSX" },
  { value: "jsx", label: "JSX" },
  { value: "makefile", label: "Makefile" },
];
