import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Session from "@/provider/Session";
import { ThemeProvider } from "@/provider/theme";
import Query from "@/provider/query-client";
import { Toaster } from "sonner";
import SmoothScrollWrapper from "@/components/custom/SmoothScrollWrapper";

const spaceGrotesk = Space_Grotesk({ weight: "600", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Share snippets",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      url: "/logo.png",
      type: "image/png",
    },
  ],
  openGraph: {
    title: "Share snippets",
    description: "Share code snippets easily.",
    images: [
      "https://res.cloudinary.com/dzf9kamfw/image/upload/v1764708285/Screenshot_from_2025-12-03_02-12-23_wp1ohu.png",
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Share snippets",
    description: "Share code snippets easily.",
    images: [
      "https://res.cloudinary.com/dzf9kamfw/image/upload/v1764708285/Screenshot_from_2025-12-03_02-12-23_wp1ohu.png",
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.className} antialiased `}
        suppressHydrationWarning
      >
        <Query>
          <Toaster richColors />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Session>{children}</Session>
          </ThemeProvider>
        </Query>
      </body>
    </html>
  );
}
