import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import Session from "@/provider/Session";
import { ThemeProvider } from "@/provider/theme";
import Query from "@/provider/query-client";
import { Toaster } from "sonner";
import SmoothScrollWrapper from "@/components/custom/SmoothScrollWrapper";

const spaceGrotesk = Space_Grotesk({ weight: "600", subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Share snippets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.className} antialiased `}
        suppressHydrationWarning
      >
        <Query>
          <Toaster richColors />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Session>{children}</Session>
          </ThemeProvider>
        </Query>
      </body>
    </html>
  );
}
